/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { BooleanCondMock } from "./BooleanCondMock";

export class BooleanCondMockFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(): Promise<BooleanCondMock> {
    return super.deploy() as Promise<BooleanCondMock>;
  }
  getDeployTransaction(): UnsignedTransaction {
    return super.getDeployTransaction();
  }
  attach(address: string): BooleanCondMock {
    return super.attach(address) as BooleanCondMock;
  }
  connect(signer: Signer): BooleanCondMockFactory {
    return super.connect(signer) as BooleanCondMockFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BooleanCondMock {
    return new Contract(address, _abi, signerOrProvider) as BooleanCondMock;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes",
        name: "_query",
        type: "bytes"
      }
    ],
    name: "isFinalized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes",
        name: "_query",
        type: "bytes"
      }
    ],
    name: "getOutcome",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101e0806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063bcdbda941461003b578063ea4ba8eb146100bf575b600080fd5b6100ab6004803603602081101561005157600080fd5b81019060208101813564010000000081111561006c57600080fd5b82018360208201111561007e57600080fd5b803590602001918460018302840111640100000000831117156100a057600080fd5b50909250905061012f565b604080519115158252519081900360200190f35b6100ab600480360360208110156100d557600080fd5b8101906020810181356401000000008111156100f057600080fd5b82018360208201111561010257600080fd5b8035906020019184600183028401116401000000008311171561012457600080fd5b509092509050610137565b600192915050565b600061017883838080601f01602080910402602001604051908101604052809392919081815260200183838082843760009201919091525061017f92505050565b9392505050565b6000815160001415610193575060006101a6565b5060208181015182519091036008021c15155b91905056fea265627a7a72315820a87aa2da00e25e1cd3fbc23168891cf9720918ee407d83da47c372365aed798464736f6c634300050c0032";
