/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface BooleanCondMockInterface extends Interface {
  functions: {
    isFinalized: TypedFunctionDescription<{
      encode([_query]: [Arrayish]): string;
    }>;

    getOutcome: TypedFunctionDescription<{
      encode([_query]: [Arrayish]): string;
    }>;
  };

  events: {};
}

export class BooleanCondMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): BooleanCondMock;
  attach(addressOrName: string): BooleanCondMock;
  deployed(): Promise<BooleanCondMock>;

  on(event: EventFilter | string, listener: Listener): BooleanCondMock;
  once(event: EventFilter | string, listener: Listener): BooleanCondMock;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): BooleanCondMock;
  removeAllListeners(eventName: EventFilter | string): BooleanCondMock;
  removeListener(eventName: any, listener: Listener): BooleanCondMock;

  interface: BooleanCondMockInterface;

  functions: {
    isFinalized(_query: Arrayish): Promise<boolean>;

    getOutcome(_query: Arrayish): Promise<boolean>;
  };

  isFinalized(_query: Arrayish): Promise<boolean>;

  getOutcome(_query: Arrayish): Promise<boolean>;

  filters: {};

  estimate: {
    isFinalized(_query: Arrayish): Promise<BigNumber>;

    getOutcome(_query: Arrayish): Promise<BigNumber>;
  };
}
