/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface CommonInterface extends Interface {
  functions: {
    getCurrentBlockNumber: TypedFunctionDescription<{ encode([]: []): string }>;

    isContract: TypedFunctionDescription<{ encode([addr]: [string]): string }>;
  };

  events: {};
}

export class Common extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Common;
  attach(addressOrName: string): Common;
  deployed(): Promise<Common>;

  on(event: EventFilter | string, listener: Listener): Common;
  once(event: EventFilter | string, listener: Listener): Common;
  addListener(eventName: EventFilter | string, listener: Listener): Common;
  removeAllListeners(eventName: EventFilter | string): Common;
  removeListener(eventName: any, listener: Listener): Common;

  interface: CommonInterface;

  functions: {
    getCurrentBlockNumber(): Promise<BigNumber>;

    isContract(addr: string): Promise<boolean>;
  };

  getCurrentBlockNumber(): Promise<BigNumber>;

  isContract(addr: string): Promise<boolean>;

  filters: {};

  estimate: {
    getCurrentBlockNumber(): Promise<BigNumber>;

    isContract(addr: string): Promise<BigNumber>;
  };
}
