/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IAccessSecretRegistryInterface extends Interface {
  functions: {
    getOutcome: TypedFunctionDescription<{
      encode([_query]: [Arrayish]): string;
    }>;

    getDID: TypedFunctionDescription<{
      encode([_key]: [BigNumberish]): string;
    }>;

    setDID: TypedFunctionDescription<{
      encode([_did, _didRegistryAddress]: [Arrayish, string]): string;
    }>;

    getKeyDID: TypedFunctionDescription<{ encode([_did]: [Arrayish]): string }>;

    checkPermissions: TypedFunctionDescription<{
      encode([user, documentKeyId]: [string, Arrayish]): string;
    }>;

    getOwner: TypedFunctionDescription<{ encode([]: []): string }>;

    getGrantee: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {
    settedDID: TypedEventDescription<{ encodeTopics([did]: [null]): string[] }>;
  };
}

export class IAccessSecretRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IAccessSecretRegistry;
  attach(addressOrName: string): IAccessSecretRegistry;
  deployed(): Promise<IAccessSecretRegistry>;

  on(event: EventFilter | string, listener: Listener): IAccessSecretRegistry;
  once(event: EventFilter | string, listener: Listener): IAccessSecretRegistry;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IAccessSecretRegistry;
  removeAllListeners(eventName: EventFilter | string): IAccessSecretRegistry;
  removeListener(eventName: any, listener: Listener): IAccessSecretRegistry;

  interface: IAccessSecretRegistryInterface;

  functions: {
    getOutcome(_query: Arrayish): Promise<boolean>;

    getDID(_key: BigNumberish): Promise<string>;

    setDID(
      _did: Arrayish,
      _didRegistryAddress: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getKeyDID(_did: Arrayish): Promise<number>;

    checkPermissions(user: string, documentKeyId: Arrayish): Promise<boolean>;

    getOwner(): Promise<string>;

    getGrantee(): Promise<string>;
  };

  getOutcome(_query: Arrayish): Promise<boolean>;

  getDID(_key: BigNumberish): Promise<string>;

  setDID(
    _did: Arrayish,
    _didRegistryAddress: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getKeyDID(_did: Arrayish): Promise<number>;

  checkPermissions(user: string, documentKeyId: Arrayish): Promise<boolean>;

  getOwner(): Promise<string>;

  getGrantee(): Promise<string>;

  filters: {
    settedDID(did: null): EventFilter;
  };

  estimate: {
    getOutcome(_query: Arrayish): Promise<BigNumber>;

    getDID(_key: BigNumberish): Promise<BigNumber>;

    setDID(_did: Arrayish, _didRegistryAddress: string): Promise<BigNumber>;

    getKeyDID(_did: Arrayish): Promise<BigNumber>;

    checkPermissions(user: string, documentKeyId: Arrayish): Promise<BigNumber>;

    getOwner(): Promise<BigNumber>;

    getGrantee(): Promise<BigNumber>;
  };
}
