/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ICelerLedger } from "./ICelerLedger";

export class ICelerLedgerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICelerLedger {
    return new Contract(address, _abi, signerOrProvider) as ICelerLedger;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "payId",
        type: "bytes32"
      },
      {
        indexed: true,
        internalType: "address",
        name: "peerFrom",
        type: "address"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256"
      }
    ],
    name: "ClearOnePay",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "settleBalance",
        type: "uint256[2]"
      }
    ],
    name: "ConfirmSettle",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      }
    ],
    name: "ConfirmSettleFail",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "withdrawnAmount",
        type: "uint256"
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address"
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "recipientChannelId",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "deposits",
        type: "uint256[2]"
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "withdrawals",
        type: "uint256[2]"
      }
    ],
    name: "ConfirmWithdraw",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "settleBalance",
        type: "uint256[2]"
      }
    ],
    name: "CooperativeSettle",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "withdrawnAmount",
        type: "uint256"
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address"
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "recipientChannelId",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "deposits",
        type: "uint256[2]"
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "withdrawals",
        type: "uint256[2]"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "seqNum",
        type: "uint256"
      }
    ],
    name: "CooperativeWithdraw",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "address[2]",
        name: "peerAddrs",
        type: "address[2]"
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "deposits",
        type: "uint256[2]"
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "withdrawals",
        type: "uint256[2]"
      }
    ],
    name: "Deposit",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "seqNums",
        type: "uint256[2]"
      }
    ],
    name: "IntendSettle",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256"
      }
    ],
    name: "IntendWithdraw",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: true,
        internalType: "address",
        name: "oldLedgerAddr",
        type: "address"
      }
    ],
    name: "MigrateChannelFrom",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: true,
        internalType: "address",
        name: "newLedgerAddr",
        type: "address"
      }
    ],
    name: "MigrateChannelTo",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenType",
        type: "uint256"
      },
      {
        indexed: true,
        internalType: "address",
        name: "tokenAddress",
        type: "address"
      },
      {
        indexed: false,
        internalType: "address[2]",
        name: "peerAddrs",
        type: "address[2]"
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "initialDeposits",
        type: "uint256[2]"
      }
    ],
    name: "OpenChannel",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      },
      {
        indexed: false,
        internalType: "uint256[2]",
        name: "seqNums",
        type: "uint256[2]"
      }
    ],
    name: "SnapshotStates",
    type: "event"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "channelId",
        type: "bytes32"
      }
    ],
    name: "VetoWithdraw",
    type: "event"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes",
        name: "_openChannelRequest",
        type: "bytes"
      }
    ],
    name: "openChannel",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      },
      {
        internalType: "address",
        name: "_receiver",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "_transferFromAmount",
        type: "uint256"
      }
    ],
    name: "deposit",
    outputs: [],
    payable: true,
    stateMutability: "payable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes32[]",
        name: "_channelIds",
        type: "bytes32[]"
      },
      {
        internalType: "address[]",
        name: "_receivers",
        type: "address[]"
      },
      {
        internalType: "uint256[]",
        name: "_transferFromAmounts",
        type: "uint256[]"
      }
    ],
    name: "depositInBatch",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes",
        name: "_signedSimplexStateArray",
        type: "bytes"
      }
    ],
    name: "snapshotStates",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256"
      },
      {
        internalType: "bytes32",
        name: "_recipientChannelId",
        type: "bytes32"
      }
    ],
    name: "intendWithdraw",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "confirmWithdraw",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "vetoWithdraw",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes",
        name: "_cooperativeWithdrawRequest",
        type: "bytes"
      }
    ],
    name: "cooperativeWithdraw",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes",
        name: "_signedSimplexStateArray",
        type: "bytes"
      }
    ],
    name: "intendSettle",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      },
      {
        internalType: "address",
        name: "_peerFrom",
        type: "address"
      },
      {
        internalType: "bytes",
        name: "_payIdList",
        type: "bytes"
      }
    ],
    name: "clearPays",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "confirmSettle",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes",
        name: "_settleRequest",
        type: "bytes"
      }
    ],
    name: "cooperativeSettle",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "_channelStatus",
        type: "uint256"
      }
    ],
    name: "getChannelStatusNum",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "getEthPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "getPayRegistry",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "getCelerWallet",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getSettleFinalizedTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getTokenContract",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getTokenType",
    outputs: [
      {
        internalType: "enum PbEntity.TokenType",
        name: "",
        type: "uint8"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getChannelStatus",
    outputs: [
      {
        internalType: "enum LedgerStruct.ChannelStatus",
        name: "",
        type: "uint8"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getCooperativeWithdrawSeqNum",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getTotalBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getBalanceMap",
    outputs: [
      {
        internalType: "address[2]",
        name: "",
        type: "address[2]"
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]"
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getChannelMigrationArgs",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      },
      {
        internalType: "address",
        name: "",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getPeersMigrationInfo",
    outputs: [
      {
        internalType: "address[2]",
        name: "",
        type: "address[2]"
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]"
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]"
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]"
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]"
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getDisputeTimeout",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getMigratedTo",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getStateSeqNumMap",
    outputs: [
      {
        internalType: "address[2]",
        name: "",
        type: "address[2]"
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getTransferOutMap",
    outputs: [
      {
        internalType: "address[2]",
        name: "",
        type: "address[2]"
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getNextPayIdListHashMap",
    outputs: [
      {
        internalType: "address[2]",
        name: "",
        type: "address[2]"
      },
      {
        internalType: "bytes32[2]",
        name: "",
        type: "bytes32[2]"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getLastPayResolveDeadlineMap",
    outputs: [
      {
        internalType: "address[2]",
        name: "",
        type: "address[2]"
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getPendingPayOutMap",
    outputs: [
      {
        internalType: "address[2]",
        name: "",
        type: "address[2]"
      },
      {
        internalType: "uint256[2]",
        name: "",
        type: "uint256[2]"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_channelId",
        type: "bytes32"
      }
    ],
    name: "getWithdrawIntent",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address[]",
        name: "_tokenAddrs",
        type: "address[]"
      },
      {
        internalType: "uint256[]",
        name: "_limits",
        type: "uint256[]"
      }
    ],
    name: "setBalanceLimits",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [],
    name: "disableBalanceLimits",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [],
    name: "enableBalanceLimits",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddr",
        type: "address"
      }
    ],
    name: "getBalanceLimit",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "getBalanceLimitsEnabled",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes",
        name: "_migrationRequest",
        type: "bytes"
      }
    ],
    name: "migrateChannelTo",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "address",
        name: "_fromLedgerAddr",
        type: "address"
      },
      {
        internalType: "bytes",
        name: "_migrationRequest",
        type: "bytes"
      }
    ],
    name: "migrateChannelFrom",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];
