/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IPayResolverInterface extends Interface {
  functions: {
    resolvePaymentByConditions: TypedFunctionDescription<{
      encode([_resolvePayRequest]: [Arrayish]): string;
    }>;

    resolvePaymentByVouchedResult: TypedFunctionDescription<{
      encode([_vouchedPayResult]: [Arrayish]): string;
    }>;
  };

  events: {
    ResolvePayment: TypedEventDescription<{
      encodeTopics([payId, amount, resolveDeadline]: [
        Arrayish | null,
        null,
        null
      ]): string[];
    }>;
  };
}

export class IPayResolver extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IPayResolver;
  attach(addressOrName: string): IPayResolver;
  deployed(): Promise<IPayResolver>;

  on(event: EventFilter | string, listener: Listener): IPayResolver;
  once(event: EventFilter | string, listener: Listener): IPayResolver;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IPayResolver;
  removeAllListeners(eventName: EventFilter | string): IPayResolver;
  removeListener(eventName: any, listener: Listener): IPayResolver;

  interface: IPayResolverInterface;

  functions: {
    resolvePaymentByConditions(
      _resolvePayRequest: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    resolvePaymentByVouchedResult(
      _vouchedPayResult: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  resolvePaymentByConditions(
    _resolvePayRequest: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  resolvePaymentByVouchedResult(
    _vouchedPayResult: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    ResolvePayment(
      payId: Arrayish | null,
      amount: null,
      resolveDeadline: null
    ): EventFilter;
  };

  estimate: {
    resolvePaymentByConditions(
      _resolvePayRequest: Arrayish
    ): Promise<BigNumber>;

    resolvePaymentByVouchedResult(
      _vouchedPayResult: Arrayish
    ): Promise<BigNumber>;
  };
}
