/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ISecretStore } from "./ISecretStore";

export class ISecretStoreFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISecretStore {
    return new Contract(address, _abi, signerOrProvider) as ISecretStore;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address"
      },
      {
        internalType: "bytes32",
        name: "documentKeyId",
        type: "bytes32"
      }
    ],
    name: "checkPermissions",
    outputs: [
      {
        internalType: "bool",
        name: "permissionGranted",
        type: "bool"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];
