/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { SingleSessionBooleanOutcome } from "./SingleSessionBooleanOutcome";

export class SingleSessionBooleanOutcomeFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SingleSessionBooleanOutcome {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SingleSessionBooleanOutcome;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_players",
        type: "address[]"
      },
      {
        internalType: "uint256",
        name: "_nonce",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "_timeout",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor"
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "seq",
        type: "uint256"
      }
    ],
    name: "IntendSettle",
    type: "event"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes",
        name: "_query",
        type: "bytes"
      }
    ],
    name: "getOutcome",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "getSeqNum",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: true,
    inputs: [],
    name: "getStatus",
    outputs: [
      {
        internalType: "enum ISingleSession.AppStatus",
        name: "",
        type: "uint8"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes",
        name: "_stateProof",
        type: "bytes"
      }
    ],
    name: "intendSettle",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes",
        name: "_query",
        type: "bytes"
      }
    ],
    name: "isFinalized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];
