/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { VirtContractResolver } from "./VirtContractResolver";

export class VirtContractResolverFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(): Promise<VirtContractResolver> {
    return super.deploy() as Promise<VirtContractResolver>;
  }
  getDeployTransaction(): UnsignedTransaction {
    return super.getDeployTransaction();
  }
  attach(address: string): VirtContractResolver {
    return super.attach(address) as VirtContractResolver;
  }
  connect(signer: Signer): VirtContractResolverFactory {
    return super.connect(signer) as VirtContractResolverFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VirtContractResolver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as VirtContractResolver;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "virtAddr",
        type: "bytes32"
      }
    ],
    name: "Deploy",
    type: "event"
  },
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes",
        name: "_code",
        type: "bytes"
      },
      {
        internalType: "uint256",
        name: "_nonce",
        type: "uint256"
      }
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "bytes32",
        name: "_virtAddr",
        type: "bytes32"
      }
    ],
    name: "resolve",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610349806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80635c23bdf51461003b5780639c4ae2d014610074575b600080fd5b6100586004803603602081101561005157600080fd5b50356100f8565b604080516001600160a01b039092168252519081900360200190f35b6100e46004803603604081101561008a57600080fd5b8101906020810181356401000000008111156100a557600080fd5b8201836020820111156100b757600080fd5b803590602001918460018302840111640100000000831117156100d957600080fd5b91935091503561017d565b604080519115158252519081900360200190f35b6000818152602081905260408120546001600160a01b0316610161576040805162461bcd60e51b815260206004820152601b60248201527f4e6f6e6578697374656e74207669727475616c20616464726573730000000000604482015290519081900360640190fd5b506000908152602081905260409020546001600160a01b031690565b600080848484604051602001808484808284379190910192835250506040805180830381526020808401808452825192820192909220601f8b018290049091028401830183528982529550606094509250889188918291018382808284376000920182905250868152602081905260409020549394505050506001600160a01b031615610251576040805162461bcd60e51b815260206004820152601d60248201527f43757272656e74207265616c2061646472657373206973206e6f742030000000604482015290519081900360640190fd5b60008151602083016000f090506001600160a01b0381166102b9576040805162461bcd60e51b815260206004820152601760248201527f43726561746520636f6e7472616374206661696c65642e000000000000000000604482015290519081900360640190fd5b60008381526020819052604080822080546001600160a01b0319166001600160a01b0385161790555184917f149208daa30a9306858cc9c171c3510e0e50ab5d59ed2027a37a728430dd02e491a2506001969550505050505056fea265627a7a723158205735614bcf8f6e027d3b86f1efe57cc4dd6e0e823cbcc63869b1420bb4e2903564736f6c634300050c0032";
